# fly.toml app configuration file generated for pic-pulse on 2023-06-19T21:13:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pic-pulse"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
